### ISSUE TITLE
Remove lodash dependency

### ISSUE THREAD

**Issue by aldeed** [aldeed/js-message-box#13]
Look for individual, small, secure, well-supported packages that could be used in place of the two `lodash` functions that are used (`merge` and `template`). Although modern build tools should be able to tree shake `lodash`, it's still best for download times and other reasons to not pull in such a large package.

**Comment by trojanh** [comment]
@aldeed how about using these?
https://www.npmjs.com/package/lodash.template
https://www.npmjs.com/package/lodash.merge

**Comment by aldeed** [comment]
Last I heard, the individual `lodash.*` packages are no longer getting security fixes. Need to look for something that is secure and maintained.

**Comment by trojanh** [comment]
Ok, I see [they were last](https://www.npmjs.com/package/lodash.merge) updated 8 months ago.

Anyway, [`deepmerge`](https://www.npmjs.com/package/deepmerge) for merge looks really solid and popular, might want to use this, if the size is still a concern for using this package you can try [js.merge](https://www.npmjs.com/package/merge). 

Also how about using [`ejs`](https://www.npmjs.com/package/ejs) or [micromustache](https://www.npmjs.com/package/micromustache) for templating?

**Comment by aldeed** [comment]
Switched to `deep-extend` and `lodash.template` in 0.2.3. I think `micromustache` would be better but I don't want to introduce breaking changes at this time.
