### ISSUE TITLE
Snyk security vulnerability due to lodash.template standalone dependency

### ISSUE THREAD

**Issue by m-a-d1** [aldeed/js-message-box#25]
Snyk reports a security vulnerability for this package because of the dependency on the lodash.template standalone package.
You can see the report here: https://security.snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054

However, it doesn't look like lodash is supporting standalone packages anymore: https://lodash.com/per-method-packages and there isn't an updated package with a security patch (besides the core lodash package).

Let me know if more details are needed.

**Comment by jesusej** [comment]
I think the best approach would be to include the core package and import only the template function like the article recommends.

<img width="1157" alt="Screenshot of lodash article which recommends to use core package and only include the functions you want to use" src="https://github.com/user-attachments/assets/8f5b0203-f6ce-4467-b6f8-b8359f8e8448">

We only would need to check if the changes between 4.5.0 and 4.17.21 could affect the functionality of the template function and do the necessary changes

**Comment by aldeed** [comment]
Resolved in v1.0.0
